create table performance_schema.table_lock_waits_summary_by_table
(
    OBJECT_TYPE                       varchar(64)     null,
    OBJECT_SCHEMA                     varchar(64)     null,
    OBJECT_NAME                       varchar(64)     null,
    COUNT_STAR                        bigint unsigned not null,
    SUM_TIMER_WAIT                    bigint unsigned not null,
    MIN_TIMER_WAIT                    bigint unsigned not null,
    AVG_TIMER_WAIT                    bigint unsigned not null,
    MAX_TIMER_WAIT                    bigint unsigned not null,
    COUNT_READ                        bigint unsigned not null,
    SUM_TIMER_READ                    bigint unsigned not null,
    MIN_TIMER_READ                    bigint unsigned not null,
    AVG_TIMER_READ                    bigint unsigned not null,
    MAX_TIMER_READ                    bigint unsigned not null,
    COUNT_WRITE                       bigint unsigned not null,
    SUM_TIMER_WRITE                   bigint unsigned not null,
    MIN_TIMER_WRITE                   bigint unsigned not null,
    AVG_TIMER_WRITE                   bigint unsigned not null,
    MAX_TIMER_WRITE                   bigint unsigned not null,
    COUNT_READ_NORMAL                 bigint unsigned not null,
    SUM_TIMER_READ_NORMAL             bigint unsigned not null,
    MIN_TIMER_READ_NORMAL             bigint unsigned not null,
    AVG_TIMER_READ_NORMAL             bigint unsigned not null,
    MAX_TIMER_READ_NORMAL             bigint unsigned not null,
    COUNT_READ_WITH_SHARED_LOCKS      bigint unsigned not null,
    SUM_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null,
    MIN_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null,
    AVG_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null,
    MAX_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null,
    COUNT_READ_HIGH_PRIORITY          bigint unsigned not null,
    SUM_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null,
    MIN_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null,
    AVG_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null,
    MAX_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null,
    COUNT_READ_NO_INSERT              bigint unsigned not null,
    SUM_TIMER_READ_NO_INSERT          bigint unsigned not null,
    MIN_TIMER_READ_NO_INSERT          bigint unsigned not null,
    AVG_TIMER_READ_NO_INSERT          bigint unsigned not null,
    MAX_TIMER_READ_NO_INSERT          bigint unsigned not null,
    COUNT_READ_EXTERNAL               bigint unsigned not null,
    SUM_TIMER_READ_EXTERNAL           bigint unsigned not null,
    MIN_TIMER_READ_EXTERNAL           bigint unsigned not null,
    AVG_TIMER_READ_EXTERNAL           bigint unsigned not null,
    MAX_TIMER_READ_EXTERNAL           bigint unsigned not null,
    COUNT_WRITE_ALLOW_WRITE           bigint unsigned not null,
    SUM_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null,
    MIN_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null,
    AVG_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null,
    MAX_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null,
    COUNT_WRITE_CONCURRENT_INSERT     bigint unsigned not null,
    SUM_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null,
    MIN_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null,
    AVG_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null,
    MAX_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null,
    COUNT_WRITE_LOW_PRIORITY          bigint unsigned not null,
    SUM_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null,
    MIN_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null,
    AVG_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null,
    MAX_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null,
    COUNT_WRITE_NORMAL                bigint unsigned not null,
    SUM_TIMER_WRITE_NORMAL            bigint unsigned not null,
    MIN_TIMER_WRITE_NORMAL            bigint unsigned not null,
    AVG_TIMER_WRITE_NORMAL            bigint unsigned not null,
    MAX_TIMER_WRITE_NORMAL            bigint unsigned not null,
    COUNT_WRITE_EXTERNAL              bigint unsigned not null,
    SUM_TIMER_WRITE_EXTERNAL          bigint unsigned not null,
    MIN_TIMER_WRITE_EXTERNAL          bigint unsigned not null,
    AVG_TIMER_WRITE_EXTERNAL          bigint unsigned not null,
    MAX_TIMER_WRITE_EXTERNAL          bigint unsigned not null,
    constraint OBJECT
        unique (OBJECT_TYPE, OBJECT_SCHEMA, OBJECT_NAME) using hash
)
    engine = PERFORMANCE_SCHEMA;

