create table mysql.user
(
    Host                     char(255) charset ascii                               default ''                      not null,
    User                     char(32)                                              default ''                      not null,
    Select_priv              enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Insert_priv              enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Update_priv              enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Delete_priv              enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_priv              enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Drop_priv                enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Reload_priv              enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Shutdown_priv            enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Process_priv             enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    File_priv                enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Grant_priv               enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    References_priv          enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Index_priv               enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Alter_priv               enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Show_db_priv             enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Super_priv               enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_tmp_table_priv    enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Lock_tables_priv         enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Execute_priv             enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Repl_slave_priv          enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Repl_client_priv         enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_view_priv         enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Show_view_priv           enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_routine_priv      enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Alter_routine_priv       enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_user_priv         enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Event_priv               enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Trigger_priv             enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_tablespace_priv   enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    ssl_type                 enum ('', 'ANY', 'X509', 'SPECIFIED') charset utf8mb3 default ''                      not null,
    ssl_cipher               blob                                                                                  not null,
    x509_issuer              blob                                                                                  not null,
    x509_subject             blob                                                                                  not null,
    max_questions            int unsigned                                          default '0'                     not null,
    max_updates              int unsigned                                          default '0'                     not null,
    max_connections          int unsigned                                          default '0'                     not null,
    max_user_connections     int unsigned                                          default '0'                     not null,
    plugin                   char(64)                                              default 'caching_sha2_password' not null,
    authentication_string    text                                                                                  null,
    password_expired         enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    password_last_changed    timestamp                                                                             null,
    password_lifetime        smallint unsigned                                                                     null,
    account_locked           enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Create_role_priv         enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Drop_role_priv           enum ('N', 'Y') charset utf8mb3                       default 'N'                     not null,
    Password_reuse_history   smallint unsigned                                                                     null,
    Password_reuse_time      smallint unsigned                                                                     null,
    Password_require_current enum ('N', 'Y') charset utf8mb3                                                       null,
    User_attributes          json                                                                                  null,
    primary key (Host, User)
)
    comment 'Users and global privileges' collate = utf8mb3_bin;

grant select on table mysql.user to 'mysql.session'@localhost;

